services:
  web:
    build: .
    container_name: booklist-app
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
    depends_on:
      - db

  db:
    container_name: booklist-db
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}